import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const script = fs.readFileSync(new URL('./学习通脚本.js', import.meta.url), 'utf8');

test('userscript uses the legacy Element Plus dialogs without the workbench', () => {
  assert.match(script, /cx-settings-dialog/);
  assert.match(script, /max-height:\s*calc\(100vh\s*-\s*24px\)/);
  assert.match(script, /overflow-y:\s*auto/);
  assert.match(script, /width:\s*min\(720px,\s*calc\(100vw\s*-\s*24px\)\)/);
  assert.match(script, /cx-runtime-dialog/);
  assert.match(script, /const App = _export_sfc/);
  assert.match(script, /const Ask = _export_sfc/);
  assert.match(script, /vue\.createApp\(App\)/);
  assert.match(script, /vue\.createApp\(Ask\)/);
  assert.match(script, /id = "xxxxzx"/);
  assert.match(script, /draggable:\s*""/);
  assert.match(script, /_unsafeWindow === _unsafeWindow\?\.top && typeof MutationObserver/);
  assert.match(script, /app\?\.unmount\(\)/);
  assert.match(script, /this\.app\?\.unmount\(\)/);
  assert.match(script, /getElementById\("cccxapp"\)\?\.remove\(\)/);
  assert.match(script, /getElementById\("xxxxzx"\)\?\.remove\(\)/);
  assert.doesNotMatch(script, /WorkbenchApp|cx-workbench|cx_workbench_layout|cx_workbench_trigger_layout/);
  assert.doesNotMatch(script, /pointerFrameState|beginResize|requestPointerFrame/);
  assert.match(script, /const extendedUserConfig = \[/);
  assert.match(script, /userConfig: \[\.\.\.userConfig, \.\.\.extendedUserConfig\]/);
  assert.match(script, /const syncConfigFromServer =/);
  assert.match(script, /formstoreObj\.saveConfig\(forminput\.value\)/);
  assert.match(script, /label: "运行框"/);
  assert.match(script, /label: "运行日志"/);
  assert.match(script, /label: "公告"/);
  assert.match(script, /allAnswer/);
  assert.match(script, /task\.video\.status/);
  assert.match(script, /left:10px;bottom:50vh/);
  assert.match(script, /#csbutton\[data-v-6ed29f7f\]\{display:none !important\}/);
  assert.match(script, /#zeokdjg\[data-v-c3c6b09f\]\{position:fixed;left:10px;right:auto;bottom:50vh/);
  assert.match(script, /question_ti/);
  assert.ok((script.match(/cx-settings-dialog/g) || []).length >= 3);
});
